# -*- coding: utf-8 -*-
"""multivariate_prognose_vba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvqmKa1g1eu2pelDqXb0XNgWvjXArYvs
"""

# DATEN LADEN – DWD Würzburg
# Zeitreihen: Wind (Kenia) | Luftdruck (Jonas) | Temperatur (Clara)
# Quelle: DWD CDC Open Data Server
# Cutoff: 01.01.2026

import io
import re
import zipfile
import requests
import pandas as pd
import numpy as np
from datetime import date

# ── Konfiguration ─────────────────────────────────────────────
STATION_ID = "05705"
BASE_URL   = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/"
CUTOFF     = date(2026, 1, 1)

# ── Hilfsfunktionen ───────────────────────────────────────────
def download_zip(url):
    print(f"  → Lade: {url}")
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    return zipfile.ZipFile(io.BytesIO(r.content))

def read_zip(zf):
    data_file = [f for f in zf.namelist() if f.startswith("produkt_")][0]
    with zf.open(data_file) as f:
        return pd.read_csv(f, sep=";", encoding="latin-1")

# ── Download ──────────────────────────────────────────────────
print("=== DWD Daten laden ===\n")

# Recent
zf_recent = download_zip(f"{BASE_URL}recent/tageswerte_KL_{STATION_ID}_akt.zip")
df_recent = read_zip(zf_recent)

# Historical
base_hist = BASE_URL + "historical/"
r         = requests.get(base_hist, timeout=30)
pattern   = rf"tageswerte_KL_{STATION_ID}_\d{{8}}_\d{{8}}_hist\.zip"
filename  = re.findall(pattern, r.text)[0]
zf_hist   = download_zip(base_hist + filename)
df_hist   = read_zip(zf_hist)

# ── Zusammenführen & Bereinigen ───────────────────────────────
df = pd.concat([df_hist, df_recent], ignore_index=True)
df.columns       = df.columns.str.strip()
df["MESS_DATUM"] = pd.to_datetime(df["MESS_DATUM"], format="%Y%m%d")
df               = df.set_index("MESS_DATUM").sort_index()
df               = df.replace(-999.0, float("nan"))
df               = df.replace(-999,   float("nan"))
df               = df[df.index.date <= CUTOFF]
df               = df[~df.index.duplicated(keep="last")]

# ── Zeitreihen extrahieren ────────────────────────────────────

# Kenia – Wind
df_wind         = df[["FM"]].copy()
df_wind.columns = ["windgeschwindigkeit_ms"]
df_wind         = df_wind.reindex(
    pd.date_range(df_wind.index[0], df_wind.index[-1], freq="D")
).interpolate(method="linear").clip(lower=0)

# Jonas – Luftdruck
df_druck         = df[["PM"]].copy()
df_druck.columns = ["luftdruck_hpa"]
df_druck         = df_druck.interpolate(method="linear")

# Clara – Temperatur
df_temp          = df[["TMK"]].copy()
df_temp.columns  = ["temperatur_mittel_c"]
df_temp          = df_temp.interpolate(method="linear")

# ── Zusammenfassung ───────────────────────────────────────────
print(f"\n{'='*55}")
print("  ÜBERSICHT DER ZEITREIHEN")
print(f"{'='*55}")

print(f"\n  Wind (Kenia):")
print(f"    Zeitraum:      {df_wind.index[0].date()} bis {df_wind.index[-1].date()}")
print(f"    Beobachtungen: {len(df_wind)}")
print(f"    Fehlende Werte: {df_wind.isna().sum().to_dict()}")

print(f"\n  Luftdruck (Jonas):")
print(f"    Zeitraum:      {df_druck.index[0].date()} bis {df_druck.index[-1].date()}")
print(f"    Beobachtungen: {len(df_druck)}")
print(f"    Fehlende Werte: {df_druck.isna().sum().to_dict()}")

print(f"\n  Temperatur (Clara):")
print(f"    Zeitraum:      {df_temp.index[0].date()} bis {df_temp.index[-1].date()}")
print(f"    Beobachtungen: {len(df_temp)}")
print(f"    Fehlende Werte: {df_temp.isna().sum().to_dict()}")

print(f"\n{'='*55}")
print("  Daten erfolgreich geladen ✅")
print(f"{'='*55}\n")

# TEIL 3 – MULTIVARIATE PIPELINE
# Automatisierte Modellselektion & Prognose
# Cutoff: 01.01.2026 | Train bis: 01.09.2025


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

# ── Konfiguration ─────────────────────────────────────────────
TRAIN_END = pd.Timestamp("2025-09-01")
DATA_END  = pd.Timestamp("2026-01-01")

# Beste Modelle aus univariater Analyse
BEST_MODELS = {
    "Wind (Kenia)":       (1, 1, 1),
    "Luftdruck (Jonas)":  (3, 1, 2),
    "Temperatur (Clara)": (1, 1, 2),
}

# Zeitreihen
ZEITREIHEN = {
    "Wind (Kenia)":       df_wind["windgeschwindigkeit_ms"],
    "Luftdruck (Jonas)":  df_druck["luftdruck_hpa"],
    "Temperatur (Clara)": df_temp["temperatur_mittel_c"],
}

print("=" * 60)
print("  TEIL 3 – Multivariate Pipeline")
print(f"  Training:  bis {TRAIN_END.date()}")
print(f"  Test:      bis {DATA_END.date()}")
print(f"  Zeitreihen: {list(ZEITREIHEN.keys())}")
print("=" * 60)

# TEIL 3 – SCHRITT 1: Evaluation der besten Modelle
# Jedes beste Modell wird auf seiner eigenen Zeitreihe
# evaluiert → Fehlertabelle für alle 3 Zeitreihen


evaluation_results = []

print("=== Schritt 1: Evaluation bester Modelle ===\n")

for name, series in ZEITREIHEN.items():
    order = BEST_MODELS[name]

    # Train/Test Split
    train = series[series.index <= TRAIN_END].interpolate()
    test  = series[(series.index > TRAIN_END) &
                   (series.index <= DATA_END)].interpolate()

    # Modell fitten und prognostizieren
    fit = ARIMA(train, order=order).fit()
    fc  = fit.forecast(steps=len(test))
    fc.index = test.index

    # Fehlermetriken
    mse  = mean_squared_error(test, fc)
    rmse = np.sqrt(mse)
    mae  = mean_absolute_error(test, fc)
    mape = np.mean(np.abs((test.values - fc.values) /
                           test.values)) * 100

    evaluation_results.append({
        "Zeitreihe": name,
        "Modell":    f"ARIMA{order}",
        "MSE":       round(mse,  4),
        "RMSE":      round(rmse, 4),
        "MAE":       round(mae,  4),
        "MAPE":      f"{round(mape, 2)}%"
    })

    print(f"  {name}: ARIMA{order}")
    print(f"    RMSE: {rmse:.4f} | MAE: {mae:.4f} | MSE: {mse:.4f}\n")

eval_df = pd.DataFrame(evaluation_results)
print("=== Übersichtstabelle ===\n")
print(eval_df.to_string(index=False))

# ============================================================
# TEIL 3 – SCHRITT 2: Bestes gemeinsames Modell finden
# Welches einzelne ARIMA Modell funktioniert am besten
# über ALLE 3 Zeitreihen?
# ============================================================

from itertools import product

print("\n=== Schritt 2: Gemeinsames Modell für alle 3 Zeitreihen ===\n")

common_results = []

for p, q in product(range(3), range(1, 4)):
    order = (p, 1, q)
    series_rmses = []
    all_ok = True

    for name, series in ZEITREIHEN.items():
        train = series[series.index <= TRAIN_END].interpolate()
        test  = series[(series.index > TRAIN_END) &
                       (series.index <= DATA_END)].interpolate()
        try:
            fit = ARIMA(train, order=order).fit()
            fc  = fit.forecast(steps=len(test))
            fc.index = test.index
            rmse = np.sqrt(mean_squared_error(test, fc))
            series_rmses.append(rmse)
        except Exception:
            all_ok = False
            break

    if all_ok:
        common_results.append({
            "Modell":          f"ARIMA{order}",
            "RMSE Wind":       round(series_rmses[0], 4),
            "RMSE Luftdruck":  round(series_rmses[1], 4),
            "RMSE Temperatur": round(series_rmses[2], 4),
            "Ø RMSE":          round(np.mean(series_rmses), 4)
        })

common_df = pd.DataFrame(common_results).sort_values("Ø RMSE").reset_index(drop=True)

print("=== Alle Modelle nach Ø RMSE über alle 3 Zeitreihen ===\n")
print(common_df.to_string(index=False))

best_common = common_df.iloc[0]["Modell"]
print(f"\n→ Bestes gemeinsames Modell: {best_common}")

# ============================================================
# TEIL 3 – SCHRITT 3: Finale Prognose mit bestem Modell
# Bestes gemeinsames Modell wird auf allen Daten gefittet
# und für alle 3 Zeitreihen prognostiziert
# ============================================================

import re

# Best common order extrahieren
nums         = re.findall(r"\d+", best_common)
common_order = (int(nums[0]), 1, int(nums[2]))

print(f"=== Finale Prognose mit {best_common} ===\n")

fig, axes = plt.subplots(3, 1, figsize=(14, 14))
forecast_results = {}

for i, (name, series) in enumerate(ZEITREIHEN.items()):

    train = series[series.index <= TRAIN_END].interpolate()
    test  = series[(series.index > TRAIN_END) &
                   (series.index <= DATA_END)].interpolate()

    # Auf allen Daten fitten
    fit    = ARIMA(series, order=common_order).fit()
    fc_obj = fit.get_forecast(steps=10)
    fc_mean = fc_obj.predicted_mean
    fc_ci   = fc_obj.conf_int(alpha=0.05)
    fc_ci.columns = ["Unteres 95% KI", "Oberes 95% KI"]

    forecast_results[name] = pd.concat(
        [fc_mean.rename("Prognose"), fc_ci], axis=1
    ).round(4)

    # Prognose auf Testperiode für Vergleich
    fit_eval = ARIMA(train, order=common_order).fit()
    fc_test  = fit_eval.forecast(steps=len(test))
    fc_test.index = test.index

    # Plot
    axes[i].plot(series[-150:], linewidth=0.7,
                 color="steelblue", label="Historisch")
    axes[i].plot(test, linewidth=1.2,
                 color="green", label="Tatsächlich (Test)")
    axes[i].plot(fc_test, linewidth=1.5, linestyle="--",
                 color="orange", label="Prognose Test")
    axes[i].plot(fc_mean, linewidth=2, marker="o",
                 color="tomato", label=f"Finale Prognose {best_common}")
    axes[i].fill_between(fc_ci.index,
                          fc_ci["Unteres 95% KI"],
                          fc_ci["Oberes 95% KI"],
                          alpha=0.3, color="tomato",
                          label="95% KI")
    axes[i].axvline(TRAIN_END, color="gray",
                    linestyle=":", linewidth=1, label="Train/Test")
    axes[i].set_title(f"{name} – {best_common}", fontsize=12)
    axes[i].set_ylabel(
        "m/s" if "Wind" in name else
        "hPa" if "Luftdruck" in name else "°C"
    )
    axes[i].legend(fontsize=8)

plt.suptitle(f"Teil 3 – Finale Prognose aller Zeitreihen ({best_common})",
             fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

# ── Prognosetabellen ──────────────────────────────────────────
print("\n=== Prognosetabellen ===\n")
for name, fc_df in forecast_results.items():
    print(f"{name}:")
    print(fc_df.to_string())
    print()