# -*- coding: utf-8 -*-
"""Wind_Datenbereinigung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXQvnc4kn5w0WmWmIS8eXuDF6yhWH0GF
"""

#Datenbereinigung

import pandas as pd
import numpy as np

# Nur FM (windgeschwindigkeit9 df_wind extrahieren
wind = df_wind["windgeschwindigkeit_ms"].copy()

print("Vor der Bereinigung")
print(f"Zeitraum:          {wind.index[0].date()} bis {wind.index[-1].date()}")
print(f"Anzahl Werte:      {len(wind)}")
print(f"Fehlende Werte:    {wind.isna().sum()}")
print(f"Negative Werte:    {(wind < 0).sum()}")
print(f"Nullwerte:         {(wind == 0).sum()}")
print(f"\nErste 5 Zeilen:\n{wind.head()}")

# ── Fehlende Werte behandeln ─────────────────────────────────
# Methode: lineare Interpolation (da nur 12 fehlende Tage)
wind_clean = wind.interpolate(method="linear")

# ── Sicherstellen dass kein negativer Wert existiert ─────────
wind_clean = wind_clean.clip(lower=0)

# ── Vollständigen Datumsindex sicherstellen ──────────────────
# (falls einzelne Tage komplett fehlen)
full_index = pd.date_range(
    start=wind_clean.index[0],
    end=wind_clean.index[-1],
    freq="D"
)
wind_clean = wind_clean.reindex(full_index)
wind_clean = wind_clean.interpolate(method="linear")

print("\n Nach der Bereinigung")
print(f"Zeitraum:          {wind_clean.index[0].date()} bis {wind_clean.index[-1].date()}")
print(f"Anzahl Werte:      {len(wind_clean)}")
print(f"Fehlende Werte:    {wind_clean.isna().sum()}")
print(f"Negative Werte:    {(wind_clean < 0).sum()}")
print(f"\nErste 5 Zeilen:\n{wind_clean.head()}")