# -*- coding: utf-8 -*-
"""wind_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17c39ASam-m14EtxKKGHxTi5EVxAlwUSg
"""

from statsmodels.tsa.stattools import adfuller, kpss
import warnings
warnings.filterwarnings("ignore")

# ── ADF Test ─────────────────────────────────────────────────
adf_result = adfuller(wind_clean, autolag="AIC")

print(" Augmented Dickey-Fuller Test (ADF) ")
print(f"H0: Die Zeitreihe hat eine Einheitswurzel (nicht stationär)")
print(f"H1: Die Zeitreihe ist stationär\n")
print(f"  Teststatistik:    {adf_result[0]:.4f}")
print(f"  p-Wert:           {adf_result[1]:.4f}")
print(f"  Lags verwendet:   {adf_result[2]}")
print(f"  Kritische Werte:")
for key, val in adf_result[4].items():
    print(f"    {key}: {val:.4f}")
if adf_result[1] < 0.05:
    print(f"\n  → p < 0.05: H0 wird abgelehnt ✅ Zeitreihe ist stationär")
else:
    print(f"\n  → p > 0.05: H0 wird nicht abgelehnt ❌ Zeitreihe ist nicht stationär")

# ── KPSS Test ────────────────────────────────────────────────
kpss_result = kpss(wind_clean, regression="c", nlags="auto")

print("\n KPSS Test ")
print(f"H0: Die Zeitreihe ist stationär")
print(f"H1: Die Zeitreihe ist nicht stationär\n")
print(f"  Teststatistik:    {kpss_result[0]:.4f}")
print(f"  p-Wert:           {kpss_result[1]:.4f}")
print(f"  Lags verwendet:   {kpss_result[2]}")
print(f"  Kritische Werte:")
for key, val in kpss_result[3].items():
    print(f"    {key}: {val:.4f}")
if kpss_result[1] > 0.05:
    print(f"\n  → p > 0.05: H0 wird nicht abgelehnt ✅ Zeitreihe ist stationär")
else:
    print(f"\n  → p < 0.05: H0 wird abgelehnt ❌ Zeitreihe ist nicht stationär")

# Schwache Stationalität ──> erste Differenz bilden
wind_diff = wind_clean.diff().dropna()

# ── ADF auf differenzierte Reihe ─────────────────────────────
adf_diff = adfuller(wind_diff, autolag="AIC")
kpss_diff = kpss(wind_diff, regression="c", nlags="auto")

print("=== Tests auf differenzierte Reihe (d=1) ===\n")
print(f"ADF  p-Wert:  {adf_diff[1]:.4f} → {'✅ Stationär' if adf_diff[1] < 0.05 else '❌ Nicht stationär'}")
print(f"KPSS p-Wert:  {kpss_diff[1]:.4f} → {'✅ Stationär' if kpss_diff[1] > 0.05 else '❌ Nicht stationär'}")

# ── Plot zum Vergleich ───────────────────────────────────────
fig, axes = plt.subplots(2, 1, figsize=(14, 6))
axes[0].plot(wind_clean, linewidth=0.4, color="steelblue")
axes[0].set_title("Original Zeitreihe")
axes[0].set_ylabel("m/s")

axes[1].plot(wind_diff, linewidth=0.4, color="tomato")
axes[1].set_title("Differenzierte Zeitreihe (d=1)")
axes[1].set_ylabel("Δm/s")
plt.tight_layout()
plt.show()

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt
# ── ACF und PACF auf der differenzierten Reihe (d=1) ─────────
fig, axes = plt.subplots(2, 1, figsize=(14, 8))

plot_acf(wind_diff, lags=40, ax=axes[0],
         title="ACF – Windgeschwindigkeit differenziert (d=1)")
plot_pacf(wind_diff, lags=40, ax=axes[1],
          title="PACF – Windgeschwindigkeit differenziert (d=1)",
          method="ywm")

plt.tight_layout()
plt.show()

from itertools import product
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# ── Split ─────────────────────────────────────────────────────
wind_train = wind_clean.iloc[:-10]
wind_test  = wind_clean.iloc[-10:]

print(f"Train: {wind_train.index[0].date()} bis {wind_train.index[-1].date()} ({len(wind_train)} Tage)")
print(f"Test:  {wind_test.index[0].date()} bis {wind_test.index[-1].date()} ({len(wind_test)} Tage)")

# ── Grid Search auf Trainingsdaten ────────────────────────────
results = []

for p, q in product(range(3), range(1, 4)):
    try:
        fit = ARIMA(wind_train, order=(p, 1, q)).fit()
        results.append({
            "Modell": f"ARIMA({p},1,{q})",
            "AIC":    round(fit.aic, 2),
            "SC":     round(fit.bic, 2),
            "HQ":     round(fit.hqic, 2)
        })
    except Exception:
        continue

results_df = pd.DataFrame(results).sort_values("SC").reset_index(drop=True)
print("\n=== Grid Search Ergebnisse (sortiert nach SC) ===\n")
print(results_df.to_string(index=False))
print(f"\n→ Bestes Modell nach SC: {results_df.iloc[0]['Modell']}")

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

FINAL_ORDER = (1, 1, 2)
N_SPLITS    = 5

tscv         = TimeSeriesSplit(n_splits=N_SPLITS)
fold_results = []

print(f"=== 5-Fold Cross Validation – ARIMA{FINAL_ORDER} ===\n")

for fold, (idx_tr, idx_te) in enumerate(tscv.split(wind_train)):
    train_fold = wind_train.iloc[idx_tr]
    test_fold  = wind_train.iloc[idx_te]
    try:
        fit  = ARIMA(train_fold, order=FINAL_ORDER).fit()
        fc   = fit.forecast(steps=len(test_fold))
        fc.index = test_fold.index
        mse  = mean_squared_error(test_fold, fc)
        rmse = np.sqrt(mse)
        mae  = mean_absolute_error(test_fold, fc)
        fold_results.append({
            "Fold":  f"Fold {fold+1}",
            "MSE":   round(mse,  4),
            "RMSE":  round(rmse, 4),
            "MAE":   round(mae,  4),
        })
        print(f"  Fold {fold+1}: RMSE={rmse:.4f} | MAE={mae:.4f}")
    except Exception as e:
        print(f"  Fold {fold+1}: Fehler — {e}")

avg_rmse = np.mean([r["RMSE"] for r in fold_results])
avg_mae  = np.mean([r["MAE"]  for r in fold_results])
avg_mse  = np.mean([r["MSE"]  for r in fold_results])

print(f"\n  Ø MSE:  {avg_mse:.4f}")
print(f"  Ø RMSE: {avg_rmse:.4f}")
print(f"  Ø MAE:  {avg_mae:.4f}")

fit_final = ARIMA(wind_train, order=FINAL_ORDER).fit()
fc_final  = fit_final.forecast(steps=len(wind_test))
fc_final.index = wind_test.index

mse_test  = mean_squared_error(wind_test, fc_final)
rmse_test = np.sqrt(mse_test)
mae_test  = mean_absolute_error(wind_test, fc_final)
mape_test = np.mean(np.abs((wind_test.values - fc_final.values) /
                             wind_test.values)) * 100

print(f"=== Finale Evaluation auf Testdaten ===\n")
print(f"  MSE:  {mse_test:.4f}")
print(f"  RMSE: {rmse_test:.4f}")
print(f"  MAE:  {mae_test:.4f}")
print(f"  MAPE: {mape_test:.4f}%")

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

FINAL_ORDER = (1, 1, 2)

# ── Fit & Forecast ────────────────────────────────────────────
fit_final  = ARIMA(wind_train, order=FINAL_ORDER).fit()
fc_obj     = fit_final.get_forecast(steps=10)
fc_mean    = fc_obj.predicted_mean
fc_ci      = fc_obj.conf_int(alpha=0.05)
fc_ci.columns = ["Unteres 95% KI", "Oberes 95% KI"]
fc_mean.index = wind_test.index
fc_ci.index   = wind_test.index

# ── Fehlermetriken ────────────────────────────────────────────
mse  = mean_squared_error(wind_test, fc_mean)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(wind_test, fc_mean)
mape = np.mean(np.abs((wind_test.values - fc_mean.values) /
                       wind_test.values)) * 100

print(f"=== Finale Evaluation ARIMA{FINAL_ORDER} ===\n")
print(f"  MSE:  {mse:.4f}")
print(f"  RMSE: {rmse:.4f}")
print(f"  MAE:  {mae:.4f}")
print(f"  MAPE: {mape:.4f}%")

# ── Tabelle ───────────────────────────────────────────────────
fc_df = pd.concat([
    fc_mean.rename("Prognose"),
    wind_test.rename("Tatsächlich"),
    fc_ci
], axis=1).round(3)
print(f"\n{fc_df.to_string()}")

# ── Plot ──────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 5))

ax.plot(wind_train[-60:], linewidth=0.8,
        color="steelblue", label="Historisch (letzte 60 Tage)")
ax.plot(wind_test, linewidth=1.5, marker="o",
        color="green", label="Tatsächlich")
ax.plot(fc_mean, linewidth=1.5, linestyle="--",
        marker="o", color="tomato",
        label=f"Prognose ARIMA{FINAL_ORDER}")
ax.fill_between(fc_ci.index,
                fc_ci["Unteres 95% KI"],
                fc_ci["Oberes 95% KI"],
                alpha=0.3, color="tomato", label="95% KI")
ax.axvline(wind_train.index[-1], color="gray",
           linestyle=":", linewidth=1.2,
           label="Train/Test Grenze")
ax.set_title("Prognose vs. Tatsächlich – Wind ARIMA(1,1,2)", fontsize=13)
ax.set_ylabel("m/s")
ax.legend()
plt.tight_layout()
plt.show()

from statsmodels.stats.diagnostic import acorr_ljungbox
from statsmodels.graphics.tsaplots import plot_acf
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# Residuen berechnen
residuals = pd.Series(fit_final.resid).dropna()

# ── Plot ──────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# Residuen über Zeit
axes[0].plot(residuals, linewidth=0.5, color="steelblue")
axes[0].axhline(0, color="tomato", linestyle="--", linewidth=0.8)
axes[0].set_title("Residuen über Zeit")
axes[0].set_ylabel("Residuum")

# ACF der Residuen
plot_acf(residuals, lags=30, ax=axes[1], title="ACF der Residuen")

# Histogramm
axes[2].hist(residuals, bins=40, color="steelblue",
             alpha=0.7, edgecolor="white")
axes[2].set_title("Verteilung der Residuen")
axes[2].set_xlabel("Residuum")

plt.suptitle("Residualanalyse – ARIMA(1,1,2) Wind", fontsize=13)
plt.tight_layout()
plt.show()

# ── Ljung-Box Test ────────────────────────────────────────────
lb = acorr_ljungbox(residuals, lags=[10, 20, 30], return_df=True)