# -*- coding: utf-8 -*-
"""Wind_deskriptive_Analyse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXQvnc4kn5w0WmWmIS8eXuDF6yhWH0GF
"""

#Deskriptive Analyse Wind

import pandas as pd
import numpy as np

# ── Grundlegende Statistiken ─────────────────────────────────
print("Deskriptive Statistiken\n")

stats = pd.DataFrame({
    "Kennzahl": [
        "Anzahl Beobachtungen",
        "Mittelwert (m/s)",
        "Median (m/s)",
        "Standardabweichung (m/s)",
        "Minimum (m/s)",
        "Maximum (m/s)",
        "25% Quantil (m/s)",
        "75% Quantil (m/s)",
        "Schiefe (Skewness)",
        "Wölbung (Kurtosis)"
    ],
    "Wert": [
        len(wind_clean),
        round(wind_clean.mean(), 4),
        round(wind_clean.median(), 4),
        round(wind_clean.std(), 4),
        round(wind_clean.min(), 4),
        round(wind_clean.max(), 4),
        round(wind_clean.quantile(0.25), 4),
        round(wind_clean.quantile(0.75), 4),
        round(wind_clean.skew(), 4),
        round(wind_clean.kurt(), 4)
    ]
})

print(stats.to_string(index=False))

# ── Analyse nach Jahrzehnt ───────────────────────────────────
print("\n Mittelwert pro Jahrzehnt \n")

wind_df = wind_clean.to_frame(name="FM")
wind_df["Jahrzehnt"] = (wind_df.index.year // 10) * 10
jahrzehnt = wind_df.groupby("Jahrzehnt")["FM"].agg(
    Mittelwert="mean",
    Std="std",
    Min="min",
    Max="max"
).round(3)

print(jahrzehnt.to_string())

# ── Analyse nach Monat ───────────────────────────────────────
print("\n Mittelwert pro Monat \n")

wind_df["Monat"] = wind_df.index.month
monate = {1:"Jan", 2:"Feb", 3:"Mär", 4:"Apr", 5:"Mai", 6:"Jun",
          7:"Jul", 8:"Aug", 9:"Sep", 10:"Okt", 11:"Nov", 12:"Dez"}

monat_stats = wind_df.groupby("Monat")["FM"].agg(
    Mittelwert="mean",
    Std="std",
    Min="min",
    Max="max"
).round(3)
monat_stats.index = monat_stats.index.map(monate)

print(monat_stats.to_string())